<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="IN-2TFWWT2" failures="2" tests="2" name="Test_All" time="50.104" errors="0" timestamp="2022-07-02T15:00:31 IST">
  <testcase classname="com.MySeleniumProject_2.testcases.CompleteVerificationScenario" name="completeVerification" time="21.558">
    <failure type="java.lang.AssertionError" message="expected [THANK YOU FOR YOUR ORDERSSSS] but found [THANK YOU FOR YOUR ORDER]">
      <![CDATA[java.lang.AssertionError: expected [THANK YOU FOR YOUR ORDERSSSS] but found [THANK YOU FOR YOUR ORDER]
at com.MySeleniumProject_2.testcases.CompleteVerificationScenario.completeVerification(CompleteVerificationScenario.java:74)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- completeVerification -->
  <testcase classname="com.MySeleniumProject_2.testcases.CompleteVerificationScenario" name="completeVerification" time="20.989">
    <failure type="java.lang.AssertionError" message="expected [THANK YOU FOR YOUR ORDERSSSS] but found [THANK YOU FOR YOUR ORDER]">
      <![CDATA[java.lang.AssertionError: expected [THANK YOU FOR YOUR ORDERSSSS] but found [THANK YOU FOR YOUR ORDER]
at com.MySeleniumProject_2.testcases.CompleteVerificationScenario.completeVerification(CompleteVerificationScenario.java:74)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- completeVerification -->
</testsuite> <!-- Test_All -->
